"""Initial migration with topic column

Revision ID: 0d0492898ec3
Revises: 
Create Date: 2026-01-10 17:45:23.023957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0492898ec3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=255), nullable=True))

    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['verified_by_fk'], ['user_id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('photo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('permanent_address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('subject_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('paper_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('is_elective',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('elective_group_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_lang')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_lang', sa.VARCHAR(length=8), nullable=True))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('elective_group_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('is_elective',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('paper_code',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('subject_code',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('permanent_address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('photo_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
