"""add role to course_assignments

Revision ID: 390fa8289215
Revises: 0d0492898ec3
Create Date: 2026-01-17 13:40:30.760429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390fa8289215'
down_revision = '0d0492898ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('topic')

    with op.batch_alter_table('course_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=16), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_lang')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_lang', sa.VARCHAR(length=8), nullable=True))

    with op.batch_alter_table('course_assignments', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
